name: Sync Fork

on:
  schedule:
    - cron: '* */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shitiomatic/forkbacon@v1.1.0
      with:
        upstream_url: "https://github.com/mriedmann/humhub-docker.git"
        upstream_branch: "master"
        branch: "master"
        method: "rebase"
        args: "--no-push"
